### ISSUE TITLE
Beacon: Document upload bug

### ISSUE THREAD

**Issue by msknee** [codeforamerica/pittsburgh-purchasing-suite#139]
Uploading a PDF to a new opportunity leads to a 500 error.

![screen shot 2015-07-28 at 10 12 05 am](https://cloud.githubusercontent.com/assets/1178390/8938075/3c54614a-3511-11e5-9c2b-5d20363b516d.png)

**Comment by bsmithgall** [comment]
Traceback:

```
2015-07-28T17:12:00.297259+00:00 app[web.1]: 2015-07-28 17:12:00,293 | purchasing.app | ERROR in app [/app/purchasing/app.py:122]: 'None' has no attribute 'get_href'
2015-07-28T17:12:00.297267+00:00 app[web.1]: Traceback (most recent call last):
2015-07-28T17:12:00.297272+00:00 app[web.1]:     response = self.full_dispatch_request()
2015-07-28T17:12:00.297270+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
2015-07-28T17:12:00.297275+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
2015-07-28T17:12:00.297277+00:00 app[web.1]:     rv = self.handle_user_exception(e)
2015-07-28T17:12:00.297279+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
2015-07-28T17:12:00.297281+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2015-07-28T17:12:00.297282+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
2015-07-28T17:12:00.297284+00:00 app[web.1]:     rv = self.dispatch_request()
2015-07-28T17:12:00.297286+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
2015-07-28T17:12:00.297290+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)
2015-07-28T17:12:00.297293+00:00 app[web.1]:   File "/app/purchasing/decorators.py", line 22, in decorated_function
2015-07-28T17:12:00.297294+00:00 app[web.1]:     return view_function(*args, **kwargs)
2015-07-28T17:12:00.297296+00:00 app[web.1]:   File "/app/purchasing/opportunities/admin/views.py", line 117, in new
2015-07-28T17:12:00.297299+00:00 app[web.1]:     categories=categories
2015-07-28T17:12:00.297302+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
2015-07-28T17:12:00.297303+00:00 app[web.1]:     context, ctx.app)
2015-07-28T17:12:00.297305+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
2015-07-28T17:12:00.297307+00:00 app[web.1]:     rv = template.render(context)
2015-07-28T17:12:00.297309+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
2015-07-28T17:12:00.297310+00:00 app[web.1]:     return self.environment.handle_exception(exc_info, True)
2015-07-28T17:12:00.297312+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
2015-07-28T17:12:00.297314+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2015-07-28T17:12:00.297316+00:00 app[web.1]:   File "/app/purchasing/templates/opportunities/admin/opportunity.html", line 2, in top-level template code
2015-07-28T17:12:00.297318+00:00 app[web.1]:     {% import "macros/with_errors.html" as macros %}
2015-07-28T17:12:00.297320+00:00 app[web.1]:   File "/app/purchasing/templates/opportunities/layout.html", line 1, in top-level template code
2015-07-28T17:12:00.297321+00:00 app[web.1]:     {% extends 'layout.html' %}
2015-07-28T17:12:00.297323+00:00 app[web.1]:   File "/app/purchasing/templates/layout.html", line 31, in top-level template code
2015-07-28T17:12:00.297325+00:00 app[web.1]:     {% block body %}
2015-07-28T17:12:00.297327+00:00 app[web.1]:   File "/app/purchasing/templates/layout.html", line 41, in block "body"
2015-07-28T17:12:00.297329+00:00 app[web.1]:     {% block content %}
2015-07-28T17:12:00.297331+00:00 app[web.1]:   File "/app/purchasing/templates/opportunities/admin/opportunity.html", line 81, in block "content"
2015-07-28T17:12:00.297333+00:00 app[web.1]:     <p><strong>Uploaded file:</strong> <a href="{{ opportunity.get_href() }}" target="_blank">{{ form.document.data }}</a> <br/></p>
2015-07-28T17:12:00.297335+00:00 app[web.1]: UndefinedError: 'None' has no attribute 'get_href'
```

This should probably be fixed by #134
